### ISSUE TITLE
Test Adapter for Google Test doesn't work with latest Visual Studio 2017 update

### ISSUE THREAD

**Issue by grandtiger** [Microsoft/TestAdapterForGoogleTest#1]
I tried to use the version published by Microsoft (v0.9.1), but I am not able to create a Google Test project following this page: https://blogs.msdn.microsoft.com/vcblog/2017/05/10/unit-testing-and-the-future-announcing-the-test-adapter-for-google-test/

The version of Visual Studio 2017 is the latest update Version 15.2 (26430.14). I happened to have another PC that is on an older version 15.2 (26430.6), and I can create a Google Test project using that older version.

Could someone look into this and fix the compatibility issue? Thanks a lot!

BTW, the error is "Creating project 'xxxx-Test1' ... project creation failed.

**Comment by LukaszMendakiewicz** [comment]
I think this is not caused by a difference in Visual Studio version, I was able to create a project successfully in 26430.14 and I am also not aware of any changes in that release that should affect this project creation scenario.

Could you compare in the Visual Studio Installer on these two machines if there is any difference in components installed?

**Comment by grandtiger** [comment]
@LukaszMendakiewicz Thanks for the info and suggestion! I checked and you were right. My Windows 10 SDK failed to install on the PC with newer version. After I downloaded and installed the SDK manually, it's working now. I am closing this issue.
